version: '3.7'
services:
  AmbrosiaDB:
    image: mongo:4.0.4 
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  Ambrosia:
    image: ambrosia:latest 
    environment:
      mongoose: mongodb://192.168.0.11:27017
      session_sercret: ducky 
      PORT: 3012
    ports:
      - 3012:3012

  Cloudflared:
    image: cloudflare/cloudflared:latest

volumes:
  mongodb_data_container:
